INSERT INTO elnat.punktersattning_typ
VALUES
    ('NATSTATION_JORDBRUKSIMPEDIMENT_6X6M'),
    ('NATSTATION_JORDBRUKSIMPEDIMENT_8X8M'),
    ('NATSTATION_JORDBRUKSIMPEDIMENT_10X10M'),
    ('NATSTATION_OVRIGMARK_6X6M'),
    ('NATSTATION_OVRIGMARK_8X8M'),
    ('NATSTATION_OVRIGMARK_10X10M'),
    ('NATSTATION_SKOG_6X6M'),
    ('NATSTATION_SKOG_8X8M'),
    ('NATSTATION_SKOG_10X10M'),
    
    ('SJOKABELSKYLT_JORDBRUKSIMPEDIMENT_6X6M'),
    ('SJOKABELSKYLT_JORDBRUKSIMPEDIMENT_8X8M'),
    ('SJOKABELSKYLT_JORDBRUKSIMPEDIMENT_10X10M'),
    ('SJOKABELSKYLT_OVRIGMARK_6X6M'),
    ('SJOKABELSKYLT_OVRIGMARK_8X8M'),
    ('SJOKABELSKYLT_OVRIGMARK_10X10M'),
    ('SJOKABELSKYLT_SKOG_6X6M'),
    ('SJOKABELSKYLT_SKOG_8X8M'),
    ('SJOKABELSKYLT_SKOG_10X10M'),
    
    ('KABELSKAP_JORDBRUKSIMPEDIMENT'),
    ('KABELSKAP_OVRIGMARK'),
    ('KABELSKAP_SKOG');

/* Vi har ingen data i prod, så vi gör det enkelt för oss och sätter alla typer till samma*/
UPDATE elnat.punktersattning
SET typ = 'KABELSKAP_SKOG';

DELETE FROM elnat.punktersattning_typ
WHERE typ = 'NATSTATION'
   OR typ = 'KABELSKAP'
   OR typ = 'SJOKABELSKYLT';
   
ALTER TABLE elnat.punktersattning
DROP COLUMN markslag;

DROP TABLE elnat.punktersattning_markslag;

ALTER TABLE elnat.punktersattning
DROP COLUMN storlek;

DROP TABLE elnat.punktersattning_storlek;