ALTER TABLE fastighet
ADD lan TEXT;

UPDATE fastighet
SET lan = 
(CASE
    WHEN kommunnamn = 'UPPLANDS VÄSBY' OR
         kommunnamn = 'VALLENTUNA' OR
         kommunnamn = 'ÖSTERÅKER' OR
         kommunnamn = 'VÄRMDÖ' OR
         kommunnamn = 'JÄRFÄLLA' OR
         kommunnamn = 'EKERÖ' OR
         kommunnamn = 'HUDDINGE' OR
         kommunnamn = 'BOTKYRKA' OR
         kommunnamn = 'SALEM' OR
         kommunnamn = 'HANINGE' OR
         kommunnamn = 'TYRESÖ' OR
         kommunnamn = 'UPPLANDS-BRO' OR
         kommunnamn = 'NYKVARN' OR
         kommunnamn = 'TÄBY' OR
         kommunnamn = 'DANDERYD' OR
         kommunnamn = 'SOLLENTUNA' OR
         kommunnamn = 'STOCKHOLM' OR
         kommunnamn = 'SÖDERTÄLJE' OR
         kommunnamn = 'NACKA' OR
         kommunnamn = 'SUNDBYBERG' OR
         kommunnamn = 'SOLNA' OR
         kommunnamn = 'LIDINGÖ' OR
         kommunnamn = 'VAXHOLM' OR
         kommunnamn = 'NORRTÄLJE' OR
         kommunnamn = 'SIGTUNA' OR
         kommunnamn = 'NYNÄSHAMN'
    THEN 'STOCKHOLM'
    WHEN kommunnamn = 'HÅBO' OR
         kommunnamn = 'ÄLVKARLEBY' OR
         kommunnamn = 'KNIVSTA' OR
         kommunnamn = 'HEBY' OR
         kommunnamn = 'TIERP' OR
         kommunnamn = 'UPPSALA' OR
         kommunnamn = 'ENKÖPING' OR
         kommunnamn = 'ÖSTHAMMAR'
    THEN 'UPPSALA'
    WHEN kommunnamn = 'VINGÅKER' OR
         kommunnamn = 'GNESTA' OR
         kommunnamn = 'NYKÖPING' OR
         kommunnamn = 'OXELÖSUND' OR
         kommunnamn = 'FLEN' OR
         kommunnamn = 'KATRINEHOLM' OR
         kommunnamn = 'ESKILSTUNA' OR
         kommunnamn = 'STRÄNGNÄS' OR
         kommunnamn = 'TROSA'
    THEN 'SÖDERMANLAND'
    WHEN kommunnamn = 'ÖDESHÖG' OR
         kommunnamn = 'YDRE' OR
         kommunnamn = 'KINDA' OR
         kommunnamn = 'BOXHOLM' OR
         kommunnamn = 'ÅTVIDABERG' OR
         kommunnamn = 'FINSPÅNG' OR
         kommunnamn = 'VALDEMARSVIK' OR
         kommunnamn = 'LINKÖPING' OR
         kommunnamn = 'NORRKÖPING' OR
         kommunnamn = 'SÖDERKÖPING' OR
         kommunnamn = 'MOTALA' OR
         kommunnamn = 'VADSTENA' OR
         kommunnamn = 'MJÖLBY'
    THEN 'ÖSTERGÖTLAND'
    WHEN kommunnamn = 'ANEBY' OR
         kommunnamn = 'GNOSJÖ' OR
         kommunnamn = 'MULLSJÖ' OR
         kommunnamn = 'HABO' OR
         kommunnamn = 'GISLAVED' OR
         kommunnamn = 'VAGGERYD' OR
         kommunnamn = 'JÖNKÖPING' OR
         kommunnamn = 'NÄSSJÖ' OR
         kommunnamn = 'VÄRNAMO' OR
         kommunnamn = 'SÄVSJÖ' OR
         kommunnamn = 'VETLANDA' OR
         kommunnamn = 'EKSJÖ' OR
         kommunnamn = 'TRANÅS'
    THEN 'JÖNKÖPING'
    WHEN kommunnamn = 'UPPVIDINGE' OR
         kommunnamn = 'LESSEBO' OR
         kommunnamn = 'TINGSRYD' OR
         kommunnamn = 'ALVESTA' OR
         kommunnamn = 'ÄLMHULT' OR
         kommunnamn = 'MARKARYD' OR
         kommunnamn = 'VÄXJÖ' OR
         kommunnamn = 'LJUNGBY'
    THEN 'KRONOBERG'
    WHEN kommunnamn = 'HÖGSBY' OR
         kommunnamn = 'TORSÅS' OR
         kommunnamn = 'MÖRBYLÅNGA' OR
         kommunnamn = 'HULTSFRED' OR
         kommunnamn = 'MÖNSTERÅS' OR
         kommunnamn = 'EMMABODA' OR
         kommunnamn = 'KALMAR' OR
         kommunnamn = 'NYBRO' OR
         kommunnamn = 'OSKARSHAMN' OR
         kommunnamn = 'VÄSTERVIK' OR
         kommunnamn = 'VIMMERBY' OR
         kommunnamn = 'BORGHOLM'
    THEN 'KALMAR'
    WHEN kommunnamn = 'GOTLAND'
    THEN 'GOTLAND'
    WHEN kommunnamn = 'OLOFSTRÖM' OR
         kommunnamn = 'KARLSKRONA' OR
         kommunnamn = 'RONNEBY' OR
         kommunnamn = 'KARLSHAMN' OR
         kommunnamn = 'SÖLVESBORG'
    THEN 'BLEKING'
    WHEN kommunnamn = 'SVALÖV' OR
         kommunnamn = 'STAFFANSTORP' OR
         kommunnamn = 'BURLÖV' OR
         kommunnamn = 'VELLINGE' OR
         kommunnamn = 'ÖSTRA GÖINGE' OR
         kommunnamn = 'ÖRKELLJUNGA' OR
         kommunnamn = 'BJUV' OR
         kommunnamn = 'KÄVLINGE' OR
         kommunnamn = 'LOMMA' OR
         kommunnamn = 'SVEDALA' OR
         kommunnamn = 'SKURUP' OR
         kommunnamn = 'SJÖBO' OR
         kommunnamn = 'HÖRBY' OR
         kommunnamn = 'HÖÖR' OR
         kommunnamn = 'TOMELILLA' OR
         kommunnamn = 'BROMÖLLA' OR
         kommunnamn = 'OSBY' OR
         kommunnamn = 'PERSTORP' OR
         kommunnamn = 'KLIPPAN' OR
         kommunnamn = 'ÅSTORP' OR
         kommunnamn = 'BÅSTAD' OR
         kommunnamn = 'MALMÖ' OR
         kommunnamn = 'LUND' OR
         kommunnamn = 'LANDSKRONA' OR
         kommunnamn = 'HELSINGBORG' OR
         kommunnamn = 'HÖGANÄS' OR
         kommunnamn = 'ESLÖV' OR
         kommunnamn = 'YSTAD' OR
         kommunnamn = 'TRELLEBORG' OR
         kommunnamn = 'KRISTIANSTAD' OR
         kommunnamn = 'SIMRISHAMN' OR
         kommunnamn = 'ÄNGELHOLM' OR
         kommunnamn = 'HÄSSLEHOLM'
    THEN 'SKÅNE'
    WHEN kommunnamn = 'HYLTE' OR
         kommunnamn = 'HALMSTAD' OR
         kommunnamn = 'LAHOLM' OR
         kommunnamn = 'FALKENBERG' OR
         kommunnamn = 'VARBERG' OR
         kommunnamn = 'KUNGSBACKA'
    THEN 'HALLAND'
    WHEN kommunnamn = 'HÄRRYDA' OR
         kommunnamn = 'PARTILLE' OR
         kommunnamn = 'ÖCKERÖ' OR
         kommunnamn = 'STENUNGSUND' OR
         kommunnamn = 'TJÖRN' OR
         kommunnamn = 'ORUST' OR
         kommunnamn = 'SOTENÄS' OR
         kommunnamn = 'MUNKEDAL' OR
         kommunnamn = 'TANUM' OR
         kommunnamn = 'DALS-ED' OR
         kommunnamn = 'FÄRGELANDA' OR
         kommunnamn = 'ALE' OR
         kommunnamn = 'LERUM' OR
         kommunnamn = 'VÅRGÅRDA' OR
         kommunnamn = 'BOLLEBYGD' OR
         kommunnamn = 'GRÄSTORP' OR
         kommunnamn = 'ESSUNGA' OR
         kommunnamn = 'KARLSBORG' OR
         kommunnamn = 'GULLSPÅNG' OR
         kommunnamn = 'TRANEMO' OR
         kommunnamn = 'BENGTSFORS' OR
         kommunnamn = 'MELLERUD' OR
         kommunnamn = 'LILLA EDET' OR
         kommunnamn = 'MARK' OR
         kommunnamn = 'SVENLJUNGA' OR
         kommunnamn = 'HERRLJUNGA' OR
         kommunnamn = 'VARA' OR
         kommunnamn = 'GÖTENE' OR
         kommunnamn = 'TIBRO' OR
         kommunnamn = 'TÖREBODA' OR
         kommunnamn = 'GÖTEBORG' OR
         kommunnamn = 'MÖLNDAL' OR
         kommunnamn = 'KUNGÄLV' OR
         kommunnamn = 'LYSEKIL' OR
         kommunnamn = 'UDDEVALLA' OR
         kommunnamn = 'STRÖMSTAD' OR
         kommunnamn = 'VÄNERSBORG' OR
         kommunnamn = 'TROLLHÄTTAN' OR
         kommunnamn = 'ALINGSÅS' OR
         kommunnamn = 'BORÅS' OR
         kommunnamn = 'ULRICEHAMN' OR
         kommunnamn = 'ÅMÅL' OR
         kommunnamn = 'MARIESTAD' OR
         kommunnamn = 'LIDKÖPING' OR
         kommunnamn = 'SKARA' OR
         kommunnamn = 'SKÖVDE' OR
         kommunnamn = 'HJO' OR
         kommunnamn = 'TIDAHOLM' OR
         kommunnamn = 'FALKÖPING'
    THEN 'VÄSTRA GÖTALAND'
    WHEN kommunnamn = 'KIL' OR
         kommunnamn = 'EDA' OR
         kommunnamn = 'TORSBY' OR
         kommunnamn = 'STORFORS' OR
         kommunnamn = 'HAMMARÖ' OR
         kommunnamn = 'MUNKFORS' OR
         kommunnamn = 'FORSHAGA' OR
         kommunnamn = 'GRUMS' OR
         kommunnamn = 'ÅRJÄNG' OR
         kommunnamn = 'SUNNE' OR
         kommunnamn = 'KARLSTAD' OR
         kommunnamn = 'KRISTINEHAMN' OR
         kommunnamn = 'FILIPSTAD' OR
         kommunnamn = 'HAGFORS' OR
         kommunnamn = 'ARVIKA' OR
         kommunnamn = 'SÄFFLE'
    THEN 'VÄRMLAND'
    WHEN kommunnamn = 'LEKEBERG' OR
         kommunnamn = 'LAXÅ' OR
         kommunnamn = 'HALLSBERG' OR
         kommunnamn = 'DEGERFORS' OR
         kommunnamn = 'HÄLLEFORS' OR
         kommunnamn = 'LJUSNARSBERG' OR
         kommunnamn = 'ÖREBRO' OR
         kommunnamn = 'KUMLA' OR
         kommunnamn = 'ASKERSUND' OR
         kommunnamn = 'KARLSKOGA' OR
         kommunnamn = 'NORA' OR
         kommunnamn = 'LINDESBERG'
    THEN 'ÖREBRO'
    WHEN kommunnamn = 'SKINNSKATTEBERG' OR
         kommunnamn = 'SURAHAMMAR' OR
         kommunnamn = 'KUNGSÖR' OR
         kommunnamn = 'HALLSTAHAMMAR' OR
         kommunnamn = 'NORBERG' OR
         kommunnamn = 'VÄSTERÅS' OR
         kommunnamn = 'SALA' OR
         kommunnamn = 'FAGERSTA' OR
         kommunnamn = 'KÖPING' OR
         kommunnamn = 'ARBOGA'
    THEN 'VÄSTMANLAND'
    WHEN kommunnamn = 'VANSBRO' OR
         kommunnamn = 'MALUNG-SÄLEN' OR
         kommunnamn = 'GAGNEF' OR
         kommunnamn = 'LEKSAND' OR
         kommunnamn = 'RÄTTVIK' OR
         kommunnamn = 'ORSA' OR
         kommunnamn = 'ÄLVDALEN' OR
         kommunnamn = 'SMEDJEBACKEN' OR
         kommunnamn = 'MORA' OR
         kommunnamn = 'FALUN' OR
         kommunnamn = 'BORLÄNGE' OR
         kommunnamn = 'SÄTER' OR
         kommunnamn = 'HEDEMORA' OR
         kommunnamn = 'AVESTA' OR
         kommunnamn = 'LUDVIKA'
    THEN 'DALARNA'
    WHEN kommunnamn = 'OCKELBO' OR
         kommunnamn = 'HOFORS' OR
         kommunnamn = 'OVANÅKER' OR
         kommunnamn = 'NORDANSTIG' OR
         kommunnamn = 'LJUSDAL' OR
         kommunnamn = 'GÄVLE' OR
         kommunnamn = 'SANDVIKEN' OR
         kommunnamn = 'SÖDERHAMN' OR
         kommunnamn = 'BOLLNÄS' OR
         kommunnamn = 'HUDIKSVALL'
    THEN 'GÄVLEBORG'
    WHEN kommunnamn = 'ÅNGE' OR
         kommunnamn = 'TIMRÅ' OR
         kommunnamn = 'HÄRNÖSAND' OR
         kommunnamn = 'SUNDSVALL' OR
         kommunnamn = 'KRAMFORS' OR
         kommunnamn = 'SOLLEFTEÅ' OR
         kommunnamn = 'ÖRNSKÖLDSVIK'
    THEN 'VÄSTERNORRLAND'
    WHEN kommunnamn = 'RAGUNDA' OR
         kommunnamn = 'BRÄCKE' OR
         kommunnamn = 'KROKOM' OR
         kommunnamn = 'STRÖMSUND' OR
         kommunnamn = 'ÅRE' OR
         kommunnamn = 'BERG' OR
         kommunnamn = 'HÄRJEDALEN' OR
         kommunnamn = 'ÖSTERSUND'
    THEN 'JÄMTLAND'
    WHEN kommunnamn = 'NORDMALING' OR
         kommunnamn = 'BJURHOLM' OR
         kommunnamn = 'VINDELN' OR
         kommunnamn = 'ROBERTSFORS' OR
         kommunnamn = 'NORSJÖ' OR
         kommunnamn = 'MALÅ' OR
         kommunnamn = 'STORUMAN' OR
         kommunnamn = 'SORSELE' OR
         kommunnamn = 'DOROTEA' OR
         kommunnamn = 'VÄNNÄS' OR
         kommunnamn = 'VILHELMINA' OR
         kommunnamn = 'ÅSELE' OR
         kommunnamn = 'UMEÅ' OR
         kommunnamn = 'LYCKSELE' OR
         kommunnamn = 'SKELLEFTEÅ'
    THEN 'VÄSTERBOTTEN'
    WHEN kommunnamn = 'ARVIDSJAUR' OR
         kommunnamn = 'ARJEPLOG' OR
         kommunnamn = 'JOKKMOKK' OR
         kommunnamn = 'ÖVERKALIX' OR
         kommunnamn = 'KALIX' OR
         kommunnamn = 'ÖVERTORNEÅ' OR
         kommunnamn = 'PAJALA' OR
         kommunnamn = 'GÄLLIVARE' OR
         kommunnamn = 'ÄLVSBYN' OR
         kommunnamn = 'LULEÅ' OR
         kommunnamn = 'PITEÅ' OR
         kommunnamn = 'BODEN' OR
         kommunnamn = 'HAPARANDA' OR
         kommunnamn = 'KIRUNA'
    THEN 'NORRBOTTEN'
    ELSE 'Okänd'
 END)