base: ../mapproxy.yaml

layers:
- name: Valdemarsvik
  title: Valdemarsviks primärkarta
  sources: [valdemarsvik_cache]
- name: Bengtsfors
  title: Bengtsfors primärkarta
  sources: [bengtsfors_cache]
- name: Falkenberg
  title: Falkenbergs primärkarta
  sources: [falkenberg_cache]

caches:
  valdemarsvik_cache:
    grids: [sweref99tm]
    sources: [valdemarsvik]
    format: image/png
  falkenberg_cache:
    grids: [sweref99tm]
    sources: [falkenberg]
    format: image/png
  bengtsfors_cache:
    grids: [sweref99tm]
    sources: [bengtsfors]
    format: image/png

sources:
  valdemarsvik:
    type: wms
    req:
      url: https://vic-metria\testpkexplorer:G65Vw4AA@gawms.vic-metria.nu/arcgis/services/Val/valdemarsvik_pk/MapServer/WMSServer
      layers: 0,1,2,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,20,21,22,23,24,25,26,28,29,30,31,32,33,34,35,36,37,38,39,40,41
      version: 1.3.0
      transparent: true
  falkenberg:
    type: wms
    req:
      url: https://vic-metria\testpkexplorer:G65Vw4AA@gawms.vic-metria.nu/arcgis/services/Fal/falkenberg_pk/MapServer/WMSServer
      layers: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,28,29,31,32,33
      version: 1.3.0
      transparent: true
  bengtsfors:
    type: wms
    req:
      url: https://vic-metria\testpkexplorer:G65Vw4AA@gawms.vic-metria.nu/arcgis/services/Ben/bengtsfors_pk/MapServer/WMSServer
      layers: 0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,28,29,30,31,33,34,35,37,38,39,41,42,43,44,45,46,47,48,49,50,51
      version: 1.3.0
      transparent: true
