export interface Country {
  name: string;
  alpha2Code: string;
}

export const COUNTRIES_SE: Country[] = [
  { name: "Afghanistan", alpha2Code: "AF" },
  { name: "Albanien", alpha2Code: "AL" },
  { name: "Algeriet", alpha2Code: "DZ" },
  { name: "Amerikanska Jungfruöarna", alpha2Code: "VI" },
  { name: "Amerikanska Samoa", alpha2Code: "AS" },
  { name: "Andorra", alpha2Code: "AD" },
  { name: "Angola", alpha2Code: "AO" },
  { name: "Anguilla", alpha2Code: "AI" },
  { name: "Antarktis", alpha2Code: "AQ" },
  { name: "Antigua och Barbuda", alpha2Code: "AG" },
  { name: "Argentina", alpha2Code: "AR" },
  { name: "Armenien", alpha2Code: "AM" },
  { name: "Aruba", alpha2Code: "AW" },
  { name: "Australien", alpha2Code: "AU" },
  { name: "Azerbajdzjan", alpha2Code: "AZ" },
  { name: "Bahamas", alpha2Code: "BS" },
  { name: "Bahrain", alpha2Code: "BH" },
  { name: "Bangladesh", alpha2Code: "BD" },
  { name: "Barbados", alpha2Code: "BB" },
  { name: "Belarus", alpha2Code: "BY" },
  { name: "Belgien", alpha2Code: "BE" },
  { name: "Belize", alpha2Code: "BZ" },
  { name: "Benin", alpha2Code: "BJ" },
  { name: "Bermuda", alpha2Code: "BM" },
  { name: "Bhutan", alpha2Code: "BT" },
  { name: "Bolivia", alpha2Code: "BO" },
  { name: "Bonaire, Sint Eustatius and Saba", alpha2Code: "BQ" },
  { name: "Bosnien och Hercegovina", alpha2Code: "BA" },
  { name: "Botswana", alpha2Code: "BW" },
  { name: "Bouvetön", alpha2Code: "BV" },
  { name: "Brasilien", alpha2Code: "BR" },
  { name: "Brittiska Jungfruöarna", alpha2Code: "VG" },
  { name: "Brittiska territoriet i Indiska Oceanen", alpha2Code: "IO" },
  { name: "Brunei", alpha2Code: "BN" },
  { name: "Bulgarien", alpha2Code: "BG" },
  { name: "Burkina Faso", alpha2Code: "BF" },
  { name: "Burundi", alpha2Code: "BI" },
  { name: "Caymanöarna", alpha2Code: "KY" },
  { name: "Centralafrikanska republiken", alpha2Code: "CF" },
  { name: "Chile", alpha2Code: "CL" },
  { name: "Colombia", alpha2Code: "CO" },
  { name: "Cooköarna", alpha2Code: "CK" },
  { name: "Costa Rica", alpha2Code: "CR" },
  { name: "Curaçao", alpha2Code: "CW" },
  { name: "Cypern", alpha2Code: "CY" },
  { name: "Danmark", alpha2Code: "DK" },
  { name: "Djibouti", alpha2Code: "DJ" },
  { name: "Dominica", alpha2Code: "DM" },
  { name: "Dominikanska republiken", alpha2Code: "DO" },
  { name: "Ecuador", alpha2Code: "EC" },
  { name: "Egypten", alpha2Code: "EG" },
  { name: "Ekvatorialguinea", alpha2Code: "GQ" },
  { name: "El Salvador", alpha2Code: "SV" },
  { name: "Elfenbenskusten", alpha2Code: "CI" },
  { name: "Eritrea", alpha2Code: "ER" },
  { name: "Estland", alpha2Code: "EE" },
  { name: "Etiopien", alpha2Code: "ET" },
  { name: "Falklandsöarna", alpha2Code: "FK" },
  { name: "Fiji", alpha2Code: "FJ" },
  { name: "Filippinerna", alpha2Code: "PH" },
  { name: "Finland", alpha2Code: "FI" },
  { name: "Frankrike", alpha2Code: "FR" },
  { name: "Franska Guyana", alpha2Code: "GF" },
  { name: "Franska Polynesien", alpha2Code: "PF" },
  { name: "Franska södra territorierna", alpha2Code: "TF" },
  { name: "Färöarna", alpha2Code: "FO" },
  { name: "Förenade Arabemiraten", alpha2Code: "AE" },
  { name: "Förenta staternas mindre öar i Oceanien och Västindien", alpha2Code: "UM" },
  { name: "Gabon", alpha2Code: "GA" },
  { name: "Gambia", alpha2Code: "GM" },
  { name: "Georgien", alpha2Code: "GE" },
  { name: "Ghana", alpha2Code: "GH" },
  { name: "Gibraltar", alpha2Code: "GI" },
  { name: "Grekland", alpha2Code: "GR" },
  { name: "Grenada", alpha2Code: "GD" },
  { name: "Grönland", alpha2Code: "GL" },
  { name: "Guadeloupe", alpha2Code: "GP" },
  { name: "Guam", alpha2Code: "GU" },
  { name: "Guatemala", alpha2Code: "GT" },
  { name: "Guernsey", alpha2Code: "GG" },
  { name: "Guinea", alpha2Code: "GN" },
  { name: "Guinea-Bissau", alpha2Code: "GW" },
  { name: "Guyana", alpha2Code: "GY" },
  { name: "Haiti", alpha2Code: "HT" },
  { name: "Heard- och McDonaldöarna", alpha2Code: "HM" },
  { name: "Honduras", alpha2Code: "HN" },
  { name: "Hongkong", alpha2Code: "HK" },
  { name: "Indien", alpha2Code: "IN" },
  { name: "Indonesien", alpha2Code: "ID" },
  { name: "Irak", alpha2Code: "IQ" },
  { name: "Iran", alpha2Code: "IR" },
  { name: "Irland", alpha2Code: "IE" },
  { name: "Island", alpha2Code: "IS" },
  { name: "Isle of Man", alpha2Code: "IM" },
  { name: "Israel", alpha2Code: "IL" },
  { name: "Italien", alpha2Code: "IT" },
  { name: "Jamaica", alpha2Code: "JM" },
  { name: "Japan", alpha2Code: "JP" },
  { name: "Jemen", alpha2Code: "YE" },
  { name: "Jersey", alpha2Code: "JE" },
  { name: "Jordanien", alpha2Code: "JO" },
  { name: "Julön", alpha2Code: "CX" },
  { name: "Kambodja", alpha2Code: "KH" },
  { name: "Kamerun", alpha2Code: "CM" },
  { name: "Kanada", alpha2Code: "CA" },
  { name: "Kap Verde", alpha2Code: "CV" },
  { name: "Kazakstan", alpha2Code: "KZ" },
  { name: "Kenya", alpha2Code: "KE" },
  { name: "Kina", alpha2Code: "CN" },
  { name: "Kirgizistan", alpha2Code: "KG" },
  { name: "Kiribati", alpha2Code: "KI" },
  { name: "Kokosöarna", alpha2Code: "CC" },
  { name: "Komorerna", alpha2Code: "KM" },
  { name: "Kongo-Brazzaville", alpha2Code: "CG" },
  { name: "Kongo-Kinshasa", alpha2Code: "CD" },
  { name: "Kroatien", alpha2Code: "HR" },
  { name: "Kuba", alpha2Code: "CU" },
  { name: "Kuwait", alpha2Code: "KW" },
  { name: "Laos", alpha2Code: "LA" },
  { name: "Lesotho", alpha2Code: "LS" },
  { name: "Lettland", alpha2Code: "LV" },
  { name: "Libanon", alpha2Code: "LB" },
  { name: "Liberia", alpha2Code: "LR" },
  { name: "Libyen", alpha2Code: "LY" },
  { name: "Liechtenstein", alpha2Code: "LI" },
  { name: "Litauen", alpha2Code: "LT" },
  { name: "Luxemburg", alpha2Code: "LU" },
  { name: "Macao", alpha2Code: "MO" },
  { name: "Madagaskar", alpha2Code: "MG" },
  { name: "Malawi", alpha2Code: "MW" },
  { name: "Malaysia", alpha2Code: "MY" },
  { name: "Maldiverna", alpha2Code: "MV" },
  { name: "Mali", alpha2Code: "ML" },
  { name: "Malta", alpha2Code: "MT" },
  { name: "Marocko", alpha2Code: "MA" },
  { name: "Marshallöarna", alpha2Code: "MH" },
  { name: "Martinique", alpha2Code: "MQ" },
  { name: "Mauretanien", alpha2Code: "MR" },
  { name: "Mauritius", alpha2Code: "MU" },
  { name: "Mayotte", alpha2Code: "YT" },
  { name: "Mexiko", alpha2Code: "MX" },
  { name: "Mikronesiska federationen", alpha2Code: "FM" },
  { name: "Moldavien", alpha2Code: "MD" },
  { name: "Monaco", alpha2Code: "MC" },
  { name: "Mongoliet", alpha2Code: "MN" },
  { name: "Montenegro", alpha2Code: "ME" },
  { name: "Montserrat", alpha2Code: "MS" },
  { name: "Moçambique", alpha2Code: "MZ" },
  { name: "Myanmar", alpha2Code: "MM" },
  { name: "Namibia", alpha2Code: "NA" },
  { name: "Nauru", alpha2Code: "NR" },
  { name: "Nederländerna", alpha2Code: "NL" },
  { name: "Nepal", alpha2Code: "NP" },
  { name: "Nicaragua", alpha2Code: "NI" },
  { name: "Niger", alpha2Code: "NE" },
  { name: "Nigeria", alpha2Code: "NG" },
  { name: "Niue", alpha2Code: "NU" },
  { name: "Nordkorea", alpha2Code: "KP" },
  { name: "Nordmakedonien", alpha2Code: "MK" },
  { name: "Nordmarianerna", alpha2Code: "MP" },
  { name: "Norfolkön", alpha2Code: "NF" },
  { name: "Norge", alpha2Code: "NO" },
  { name: "Nya Kaledonien", alpha2Code: "NC" },
  { name: "Nya Zeeland", alpha2Code: "NZ" },
  { name: "Oman", alpha2Code: "OM" },
  { name: "Pakistan", alpha2Code: "PK" },
  { name: "Palau", alpha2Code: "PW" },
  { name: "Palestina", alpha2Code: "PS" },
  { name: "Panama", alpha2Code: "PA" },
  { name: "Papua Nya Guinea", alpha2Code: "PG" },
  { name: "Paraguay", alpha2Code: "PY" },
  { name: "Peru", alpha2Code: "PE" },
  { name: "Pitcairnöarna", alpha2Code: "PN" },
  { name: "Polen", alpha2Code: "PL" },
  { name: "Portugal", alpha2Code: "PT" },
  { name: "Puerto Rico", alpha2Code: "PR" },
  { name: "Qatar", alpha2Code: "QA" },
  { name: "Rumänien", alpha2Code: "RO" },
  { name: "Rwanda", alpha2Code: "RW" },
  { name: "Ryssland", alpha2Code: "RU" },
  { name: "Réunion", alpha2Code: "RE" },
  { name: "Saint Kitts och Nevis", alpha2Code: "KN" },
  { name: "Saint Lucia", alpha2Code: "LC" },
  { name: "Saint Vincent och Grenadinerna", alpha2Code: "VC" },
  { name: "Saint-Barthélemy", alpha2Code: "BL" },
  { name: "Saint-Martin", alpha2Code: "MF" },
  { name: "Saint-Pierre och Miquelon", alpha2Code: "PM" },
  { name: "Salomonöarna", alpha2Code: "SB" },
  { name: "Samoa", alpha2Code: "WS" },
  { name: "San Marino", alpha2Code: "SM" },
  { name: "Sankta Helena", alpha2Code: "SH" },
  { name: "Saudiarabien", alpha2Code: "SA" },
  { name: "Schweiz", alpha2Code: "CH" },
  { name: "Senegal", alpha2Code: "SN" },
  { name: "Serbien", alpha2Code: "RS" },
  { name: "Seychellerna", alpha2Code: "SC" },
  { name: "Sierra Leone", alpha2Code: "SL" },
  { name: "Singapore", alpha2Code: "SG" },
  { name: "Sint Maarten", alpha2Code: "SX" },
  { name: "Slovakien", alpha2Code: "SK" },
  { name: "Slovenien", alpha2Code: "SI" },
  { name: "Somalia", alpha2Code: "SO" },
  { name: "Spanien", alpha2Code: "ES" },
  { name: "Sri Lanka", alpha2Code: "LK" },
  { name: "Storbritannien", alpha2Code: "GB" },
  { name: "Sudan", alpha2Code: "SD" },
  { name: "Surinam", alpha2Code: "SR" },
  { name: "Svalbard och Jan Mayen", alpha2Code: "SJ" },
  { name: "Sverige", alpha2Code: "SE" },
  { name: "Swaziland", alpha2Code: "SZ" },
  { name: "Sydafrika", alpha2Code: "ZA" },
  { name: "Sydgeorgien", alpha2Code: "GS" },
  { name: "Sydkorea", alpha2Code: "KR" },
  { name: "Sydsudan", alpha2Code: "SS" },
  { name: "Syrien", alpha2Code: "SY" },
  { name: "São Tomé och Príncipe", alpha2Code: "ST" },
  { name: "Tadzjikistan", alpha2Code: "TJ" },
  { name: "Taiwan", alpha2Code: "TW" },
  { name: "Tanzania", alpha2Code: "TZ" },
  { name: "Tchad", alpha2Code: "TD" },
  { name: "Thailand", alpha2Code: "TH" },
  { name: "Tjeckien", alpha2Code: "CZ" },
  { name: "Togo", alpha2Code: "TG" },
  { name: "Tokelauöarna", alpha2Code: "TK" },
  { name: "Tonga", alpha2Code: "TO" },
  { name: "Trinidad och Tobago", alpha2Code: "TT" },
  { name: "Tunisien", alpha2Code: "TN" },
  { name: "Turkiet", alpha2Code: "TR" },
  { name: "Turkmenistan", alpha2Code: "TM" },
  { name: "Turks- och Caicosöarna", alpha2Code: "TC" },
  { name: "Tuvalu", alpha2Code: "TV" },
  { name: "Tyskland", alpha2Code: "DE" },
  { name: "USA", alpha2Code: "US" },
  { name: "Uganda", alpha2Code: "UG" },
  { name: "Ukraina", alpha2Code: "UA" },
  { name: "Ungern", alpha2Code: "HU" },
  { name: "Uruguay", alpha2Code: "UY" },
  { name: "Uzbekistan", alpha2Code: "UZ" },
  { name: "Vanuatu", alpha2Code: "VU" },
  { name: "Vatikanstaten", alpha2Code: "VA" },
  { name: "Venezuela", alpha2Code: "VE" },
  { name: "Vietnam", alpha2Code: "VN" },
  { name: "Västsahara", alpha2Code: "EH" },
  { name: "Wallis- och Futunaöarna", alpha2Code: "WF" },
  { name: "Zambia", alpha2Code: "ZM" },
  { name: "Zimbabwe", alpha2Code: "ZW" },
  { name: "Åland", alpha2Code: "AX" },
  { name: "Österrike", alpha2Code: "AT" },
  { name: "Östtimor", alpha2Code: "TL" }
];
