openapi: 3.0.0
info:
  title: Dokument-converter API
  description: Api för dokumentkonverterare
  version: 0.1.0
servers:
  - url: http://localhost:9019/api
paths:
  '/pdf':
    post:
      tags:
        - pdf
      summary: Konvertera ett dokument till pdf
      operationId: "convertToPDF"
      requestBody:
        description: Dokument att konverterade
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  description: Dokumentet
                  type: string
                  format: binary
      responses:
        200:
          description: Det konverterade dokumentet
          content:
            application/pdf:
              schema:
                type: string
                format: binary