\set ON_ERROR_STOP
\set ECHO all
BEGIN;
\set ECHO all
CREATE SEQUENCE "matdatabas"."analys_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "matdatabas"."analys"."id";
CREATE SEQUENCE "matdatabas"."anvandare_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "matdatabas"."anvandare"."id";
CREATE SEQUENCE "matdatabas"."anvandargrupp_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "matdatabas"."anvandargrupp"."id";
CREATE SEQUENCE "matdatabas"."bifogad_fil_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "matdatabas"."bifogad_fil"."id";
CREATE SEQUENCE "matdatabas"."definition_matningstyp_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "matdatabas"."definition_matningstyp"."id";
CREATE SEQUENCE "matdatabas"."gransvarde_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "matdatabas"."gransvarde"."id";
CREATE SEQUENCE "matdatabas"."grupp_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "matdatabas"."grupp"."id";
CREATE SEQUENCE "matdatabas"."handelse_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "matdatabas"."handelse"."id";
CREATE SEQUENCE "matdatabas"."kartlager_fil_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "matdatabas"."kartlager_fil"."id";
CREATE SEQUENCE "matdatabas"."kartlager_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "matdatabas"."kartlager"."id";
CREATE SEQUENCE "matdatabas"."larm_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "matdatabas"."larm"."id";
CREATE SEQUENCE "matdatabas"."larmniva_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "matdatabas"."larmniva"."id";
CREATE SEQUENCE "matdatabas"."matning_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "matdatabas"."matning"."id";
CREATE SEQUENCE "matdatabas"."matningslogg_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "matdatabas"."matningslogg"."id";
CREATE SEQUENCE "matdatabas"."matningstyp_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "matdatabas"."matningstyp"."id";
CREATE SEQUENCE "matdatabas"."matobjekt_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "matdatabas"."matobjekt"."id";
CREATE SEQUENCE "matdatabas"."matrunda_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "matdatabas"."matrunda"."id";
CREATE SEQUENCE "matdatabas"."meddelanden_startsida_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "matdatabas"."meddelanden_startsida"."id";
CREATE SEQUENCE "matdatabas"."systemlogg_id_seq" INCREMENT BY 1 MINVALUE 1 START WITH 1 OWNED BY "matdatabas"."systemlogg"."id";
ALTER TABLE "matdatabas"."analys" ADD CONSTRAINT "pk_analys" PRIMARY KEY ("id");
ALTER TABLE "matdatabas"."anvandare" ADD CONSTRAINT "pk_anvandare" PRIMARY KEY ("id");
ALTER TABLE "matdatabas"."anvandargrupp" ADD CONSTRAINT "pk_anvandargrupp" PRIMARY KEY ("id");
ALTER TABLE "matdatabas"."bifogad_fil" ADD CONSTRAINT "pk_bifogad_fil" PRIMARY KEY ("id");
ALTER TABLE "matdatabas"."definition_matningstyp" ADD CONSTRAINT "pk_matningstyp_definition" PRIMARY KEY ("id");
ALTER TABLE "matdatabas"."gransvarde" ADD CONSTRAINT "pk_gransvarde" PRIMARY KEY ("id");
ALTER TABLE "matdatabas"."grupp" ADD CONSTRAINT "pk_grupp" PRIMARY KEY ("id");
ALTER TABLE "matdatabas"."handelse" ADD CONSTRAINT "pk_handelselogg" PRIMARY KEY ("id");
ALTER TABLE "matdatabas"."kartlager" ADD CONSTRAINT "pk_kartlager" PRIMARY KEY ("id");
ALTER TABLE "matdatabas"."kartlager_fil" ADD CONSTRAINT "pk_kartlager_fil" PRIMARY KEY ("id");
ALTER TABLE "matdatabas"."larm" ADD CONSTRAINT "pk_larm" PRIMARY KEY ("id");
ALTER TABLE "matdatabas"."larmniva" ADD CONSTRAINT "pk_larmniva" PRIMARY KEY ("id");
ALTER TABLE "matdatabas"."matning" ADD CONSTRAINT "pk_matning" PRIMARY KEY ("id");
ALTER TABLE "matdatabas"."matningslogg" ADD CONSTRAINT "pk_matningslogg" PRIMARY KEY ("id");
ALTER TABLE "matdatabas"."matningstyp" ADD CONSTRAINT "pk_matnings_typ" PRIMARY KEY ("id");
ALTER TABLE "matdatabas"."matobjekt" ADD CONSTRAINT "pk_matobjekt" PRIMARY KEY ("id");
ALTER TABLE "matdatabas"."matrunda" ADD CONSTRAINT "pk_matrunda" PRIMARY KEY ("id");
ALTER TABLE "matdatabas"."meddelanden_startsida" ADD CONSTRAINT "pk_meddelanden_startsida" PRIMARY KEY ("id");
ALTER TABLE "matdatabas"."systemlogg" ADD CONSTRAINT "pk_systemlogg" PRIMARY KEY ("id");
ALTER TABLE "matdatabas"."anvandare" ADD CONSTRAINT "uq_anvandare_inloggnings_namn" UNIQUE ("inloggnings_namn");
ALTER TABLE "matdatabas"."anvandargrupp" ADD CONSTRAINT "uq_anvandargrupp_namn" UNIQUE ("namn");
ALTER TABLE "matdatabas"."grupp" ADD CONSTRAINT "uq_grupp_namn" UNIQUE ("namn");
ALTER TABLE "matdatabas"."kartlager" ADD CONSTRAINT "uq_kartlager_namn" UNIQUE ("namn");
ALTER TABLE "matdatabas"."larmniva" ADD CONSTRAINT "uq_larmniva_namn" UNIQUE ("namn");
ALTER TABLE "matdatabas"."matobjekt" ADD CONSTRAINT "uq_matobjekt_namn" UNIQUE ("namn");
ALTER TABLE "matdatabas"."matrunda" ADD CONSTRAINT "uq_matrunda_namn" UNIQUE ("namn");
ALTER TABLE "matdatabas"."analys" ADD CONSTRAINT "fk_analys_matobjekt" FOREIGN KEY ("matobjekt_id") REFERENCES "matdatabas"."matobjekt" ( "id");
ALTER TABLE "matdatabas"."analys_bifogad_rapport" ADD CONSTRAINT "fk_analys_bifogad_rapport_analys" FOREIGN KEY ("analys_id") REFERENCES "matdatabas"."analys" ( "id");
ALTER TABLE "matdatabas"."analys_bifogad_rapport" ADD CONSTRAINT "fk_analys_bifogad_rapport_bifogad_fil" FOREIGN KEY ("bifogad_fil_id") REFERENCES "matdatabas"."bifogad_fil" ( "id");
ALTER TABLE "matdatabas"."anvandare" ADD CONSTRAINT "fk_anvandare_kartlager" FOREIGN KEY ("default_kartlager_id") REFERENCES "matdatabas"."kartlager" ( "id");
ALTER TABLE "matdatabas"."anvandargrupp_anvandare" ADD CONSTRAINT "fk_anvandargrupp_anvandare_anvandare" FOREIGN KEY ("anvandar_id") REFERENCES "matdatabas"."anvandare" ( "id");
ALTER TABLE "matdatabas"."anvandargrupp_anvandare" ADD CONSTRAINT "fk_anvandargrupp_anvandare_anvandargrupp" FOREIGN KEY ("anvandargrupp_id") REFERENCES "matdatabas"."anvandargrupp" ( "id");
ALTER TABLE "matdatabas"."gransvarde" ADD CONSTRAINT "fk_gransvarde_anvandargrupp" FOREIGN KEY ("larm_till_anvandargrupp_id") REFERENCES "matdatabas"."anvandargrupp" ( "id");
ALTER TABLE "matdatabas"."gransvarde" ADD CONSTRAINT "fk_gransvarde_larmniva" FOREIGN KEY ("larmniva_id") REFERENCES "matdatabas"."larmniva" ( "id");
ALTER TABLE "matdatabas"."gransvarde" ADD CONSTRAINT "fk_gransvarde_matningstyp" FOREIGN KEY ("matningstyp_id") REFERENCES "matdatabas"."matningstyp" ( "id");
ALTER TABLE "matdatabas"."grupp_matobjekt" ADD CONSTRAINT "fk_matobjekt_grupp_grupp" FOREIGN KEY ("grupp_id") REFERENCES "matdatabas"."grupp" ( "id");
ALTER TABLE "matdatabas"."grupp_matobjekt" ADD CONSTRAINT "fk_matobjekt_grupp_matobjekt" FOREIGN KEY ("matobjekt_id") REFERENCES "matdatabas"."matobjekt" ( "id");
ALTER TABLE "matdatabas"."handelse" ADD CONSTRAINT "fk_handelse_matobjekt" FOREIGN KEY ("matobjekt_id") REFERENCES "matdatabas"."matobjekt" ( "id");
ALTER TABLE "matdatabas"."handelse_bifogad_bild" ADD CONSTRAINT "fk_handelse_bifogad_bild_bifogad_fil" FOREIGN KEY ("bifogad_fil_id") REFERENCES "matdatabas"."bifogad_fil" ( "id");
ALTER TABLE "matdatabas"."handelse_bifogad_bild" ADD CONSTRAINT "fk_handelse_bifogad_bild_handelse" FOREIGN KEY ("handelse_id") REFERENCES "matdatabas"."handelse" ( "id");
ALTER TABLE "matdatabas"."kartlager_fil" ADD CONSTRAINT "fk_kartlager_fil_kartlager" FOREIGN KEY ("kartlager_id") REFERENCES "matdatabas"."kartlager" ( "id");
ALTER TABLE "matdatabas"."larm" ADD CONSTRAINT "fk_larm_gransvarde" FOREIGN KEY ("gransvarde_id") REFERENCES "matdatabas"."gransvarde" ( "id");
ALTER TABLE "matdatabas"."larm" ADD CONSTRAINT "fk_larm_matning" FOREIGN KEY ("matning_id") REFERENCES "matdatabas"."matning" ( "id");
ALTER TABLE "matdatabas"."matning" ADD CONSTRAINT "fk_matning_matningstyp" FOREIGN KEY ("matningstyp_id") REFERENCES "matdatabas"."matningstyp" ( "id");
ALTER TABLE "matdatabas"."matningslogg" ADD CONSTRAINT "fk_matningslogg_matning" FOREIGN KEY ("matning_id") REFERENCES "matdatabas"."matning" ( "id");
ALTER TABLE "matdatabas"."matningstyp" ADD CONSTRAINT "fk_matnings_typ_matobjekt" FOREIGN KEY ("matobjekt_id") REFERENCES "matdatabas"."matobjekt" ( "id");
ALTER TABLE "matdatabas"."matningstyp" ADD CONSTRAINT "fk_matningstyp_anvandargrupp" FOREIGN KEY ("matansvarig_anvandargrupp_id") REFERENCES "matdatabas"."anvandargrupp" ( "id");
ALTER TABLE "matdatabas"."matningstyp" ADD CONSTRAINT "fk_matningstyp_definition_matningstyp" FOREIGN KEY ("definition_matningstyp_id") REFERENCES "matdatabas"."definition_matningstyp" ( "id");
ALTER TABLE "matdatabas"."matobjekt" ADD CONSTRAINT "fk_matobjekt_bifogad_fil" FOREIGN KEY ("bifogad_bild_id") REFERENCES "matdatabas"."bifogad_fil" ( "id");
ALTER TABLE "matdatabas"."matobjekt_bifogat_dokument" ADD CONSTRAINT "fk_matobjekt_dokument_bifogad_fil" FOREIGN KEY ("bifogad_fil_id") REFERENCES "matdatabas"."bifogad_fil" ( "id");
ALTER TABLE "matdatabas"."matobjekt_bifogat_dokument" ADD CONSTRAINT "fk_matobjekt_dokument_matobjekt" FOREIGN KEY ("matobjekt_id") REFERENCES "matdatabas"."matobjekt" ( "id");
ALTER TABLE "matdatabas"."matrunda_matningstyp" ADD CONSTRAINT "fk_matrunda_matningstyp_matningstyp" FOREIGN KEY ("matningstyp_id") REFERENCES "matdatabas"."matningstyp" ( "id");
ALTER TABLE "matdatabas"."matrunda_matningstyp" ADD CONSTRAINT "fk_matrunda_matningstyp_matrunda" FOREIGN KEY ("matrunda_id") REFERENCES "matdatabas"."matrunda" ( "id");
ALTER TABLE "matdatabas"."analys" ALTER COLUMN "id" SET DEFAULT nextval('"matdatabas"."analys_id_seq"');
ALTER TABLE "matdatabas"."anvandare" ALTER COLUMN "aktiv" SET DEFAULT true;
ALTER TABLE "matdatabas"."anvandare" ALTER COLUMN "id" SET DEFAULT nextval('"matdatabas"."anvandare_id_seq"');
ALTER TABLE "matdatabas"."anvandare" ALTER COLUMN "skicka_epost" SET DEFAULT false;
ALTER TABLE "matdatabas"."anvandargrupp" ALTER COLUMN "id" SET DEFAULT nextval('"matdatabas"."anvandargrupp_id_seq"');
ALTER TABLE "matdatabas"."bifogad_fil" ALTER COLUMN "id" SET DEFAULT nextval('"matdatabas"."bifogad_fil_id_seq"');
ALTER TABLE "matdatabas"."definition_matningstyp" ALTER COLUMN "decimaler" SET DEFAULT 4;
ALTER TABLE "matdatabas"."definition_matningstyp" ALTER COLUMN "felkoder" SET DEFAULT 'Hinder, Annat fel';
ALTER TABLE "matdatabas"."definition_matningstyp" ALTER COLUMN "graftyp" SET DEFAULT 0;
ALTER TABLE "matdatabas"."definition_matningstyp" ALTER COLUMN "id" SET DEFAULT nextval('"matdatabas"."definition_matningstyp_id_seq"');
ALTER TABLE "matdatabas"."gransvarde" ALTER COLUMN "id" SET DEFAULT nextval('"matdatabas"."gransvarde_id_seq"');
ALTER TABLE "matdatabas"."grupp" ALTER COLUMN "id" SET DEFAULT nextval('"matdatabas"."grupp_id_seq"');
ALTER TABLE "matdatabas"."grupp" ALTER COLUMN "kartsymbol" SET DEFAULT 0;
ALTER TABLE "matdatabas"."handelse" ALTER COLUMN "id" SET DEFAULT nextval('"matdatabas"."handelse_id_seq"');
ALTER TABLE "matdatabas"."kartlager" ALTER COLUMN "direktlank" SET DEFAULT false;
ALTER TABLE "matdatabas"."kartlager" ALTER COLUMN "id" SET DEFAULT nextval('"matdatabas"."kartlager_id_seq"');
ALTER TABLE "matdatabas"."kartlager" ALTER COLUMN "visa" SET DEFAULT true;
ALTER TABLE "matdatabas"."kartlager_fil" ALTER COLUMN "id" SET DEFAULT nextval('"matdatabas"."kartlager_fil_id_seq"');
ALTER TABLE "matdatabas"."larm" ALTER COLUMN "id" SET DEFAULT nextval('"matdatabas"."larm_id_seq"');
ALTER TABLE "matdatabas"."larm" ALTER COLUMN "status" SET DEFAULT 0;
ALTER TABLE "matdatabas"."larmniva" ALTER COLUMN "id" SET DEFAULT nextval('"matdatabas"."larmniva_id_seq"');
ALTER TABLE "matdatabas"."matning" ALTER COLUMN "id" SET DEFAULT nextval('"matdatabas"."matning_id_seq"');
ALTER TABLE "matdatabas"."matning" ALTER COLUMN "inom_detektionsomrade" SET DEFAULT 1;
ALTER TABLE "matdatabas"."matning" ALTER COLUMN "status" SET DEFAULT 0;
ALTER TABLE "matdatabas"."matningslogg" ALTER COLUMN "id" SET DEFAULT nextval('"matdatabas"."matningslogg_id_seq"');
ALTER TABLE "matdatabas"."matningstyp" ALTER COLUMN "aktiv" SET DEFAULT true;
ALTER TABLE "matdatabas"."matningstyp" ALTER COLUMN "granskas_automatiskt" SET DEFAULT false;
ALTER TABLE "matdatabas"."matningstyp" ALTER COLUMN "id" SET DEFAULT nextval('"matdatabas"."matningstyp_id_seq"');
ALTER TABLE "matdatabas"."matningstyp" ALTER COLUMN "paminnelse_dagar" SET DEFAULT 3;
ALTER TABLE "matdatabas"."matobjekt" ALTER COLUMN "aktiv" SET DEFAULT true;
ALTER TABLE "matdatabas"."matobjekt" ALTER COLUMN "id" SET DEFAULT nextval('"matdatabas"."matobjekt_id_seq"');
ALTER TABLE "matdatabas"."matobjekt" ALTER COLUMN "kontrollprogram" SET DEFAULT false;
ALTER TABLE "matdatabas"."matrunda" ALTER COLUMN "aktiv" SET DEFAULT false;
ALTER TABLE "matdatabas"."matrunda" ALTER COLUMN "id" SET DEFAULT nextval('"matdatabas"."matrunda_id_seq"');
ALTER TABLE "matdatabas"."matrunda_matningstyp" ALTER COLUMN "ordning" SET DEFAULT 0;
ALTER TABLE "matdatabas"."meddelanden_startsida" ALTER COLUMN "id" SET DEFAULT nextval('"matdatabas"."meddelanden_startsida_id_seq"');
ALTER TABLE "matdatabas"."systemlogg" ALTER COLUMN "id" SET DEFAULT nextval('"matdatabas"."systemlogg_id_seq"');
select setval('"matdatabas"."analys_id_seq"',(select max("id") from "matdatabas"."analys")::bigint);
select setval('"matdatabas"."anvandare_id_seq"',(select max("id") from "matdatabas"."anvandare")::bigint);
select setval('"matdatabas"."anvandargrupp_id_seq"',(select max("id") from "matdatabas"."anvandargrupp")::bigint);
select setval('"matdatabas"."bifogad_fil_id_seq"',(select max("id") from "matdatabas"."bifogad_fil")::bigint);
select setval('"matdatabas"."definition_matningstyp_id_seq"',(select max("id") from "matdatabas"."definition_matningstyp")::bigint);
select setval('"matdatabas"."gransvarde_id_seq"',(select max("id") from "matdatabas"."gransvarde")::bigint);
select setval('"matdatabas"."grupp_id_seq"',(select max("id") from "matdatabas"."grupp")::bigint);
select setval('"matdatabas"."handelse_id_seq"',(select max("id") from "matdatabas"."handelse")::bigint);
select setval('"matdatabas"."kartlager_fil_id_seq"',(select max("id") from "matdatabas"."kartlager_fil")::bigint);
select setval('"matdatabas"."kartlager_id_seq"',(select max("id") from "matdatabas"."kartlager")::bigint);
select setval('"matdatabas"."larm_id_seq"',(select max("id") from "matdatabas"."larm")::bigint);
select setval('"matdatabas"."larmniva_id_seq"',(select max("id") from "matdatabas"."larmniva")::bigint);
select setval('"matdatabas"."matning_id_seq"',(select max("id") from "matdatabas"."matning")::bigint);
select setval('"matdatabas"."matningslogg_id_seq"',(select max("id") from "matdatabas"."matningslogg")::bigint);
select setval('"matdatabas"."matningstyp_id_seq"',(select max("id") from "matdatabas"."matningstyp")::bigint);
select setval('"matdatabas"."matobjekt_id_seq"',(select max("id") from "matdatabas"."matobjekt")::bigint);
select setval('"matdatabas"."matrunda_id_seq"',(select max("id") from "matdatabas"."matrunda")::bigint);
select setval('"matdatabas"."meddelanden_startsida_id_seq"',(select max("id") from "matdatabas"."meddelanden_startsida")::bigint);
select setval('"matdatabas"."systemlogg_id_seq"',(select max("id") from "matdatabas"."systemlogg")::bigint);
COMMIT;
